# language: haskell

# See http://www.reddit.com/r/haskell/comments/1os3f6/how_to_use_travisci_with_multiple_ghc_versions/

env:
 - GHCVER=7.10.3
 - GHCVER=8.0.2
 - GHCVER=8.2.1

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.22 ghc-$GHCVER libpq-dev
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.22 update
 - cabal-1.22 install --only-dependencies

script:
 - cabal-1.22 configure
 - cabal-1.22 build
 - cabal-1.22 check
 - cabal-1.22 haddock
 - cabal-1.22 sdist
